// ERROR ACTIONS
export const GET_ERRORS = 'GET_ERRORS';

// PROJECT ACTIONS
export const GET_PROJECTS = 'GET_PROJECTS';
export const GET_PROJECT = 'GET_PROJECTs';
export const DELETE_PROJECT = 'DELETE_PROJECT';
export const ASSIGN_USER_TO_PROJECT = 'ASSIGN_USER_PROJECT';
export const REMOVE_USER_FROM_PROJECT = 'REMOVE_USER_FROM_PROJECT';
export const GET_USERS_BY_PROJECT = 'GET_USERS_BY_PROJECT';

// BACKLOG ACTIONS
export const GET_BACKLOG = 'GET_BACKLOG';
export const GET_TASK = 'GET_TASK';
export const DELETE_TASK = 'DELETE_TASK';
export const ASSIGN_USER_TO_TASK = 'ASSIGN_USER_TASK';

// AUTH ACTIONS
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const LOGOUT = 'LOGOUT';

// USER ACTIONS
export const GET_USERS = 'GET_USERS';
export const GET_ROLES = 'GET_ROLES';
export const PROMOTE_USER = 'PROMOTE_USER';
export const DELETE_USER = 'DELETE_USER';
export const ACTIVATE_USER = 'ACTIVATE_USER';
export const DEACTIVATE_USER = 'DEACTIVATE_USER';

// COMMENT ACTIONS
export const CREATE_COMMENT = 'CREATE_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';
